services:
  e2e:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
    depends_on:
      - reservations
      - auth
      - payments
      - notifications
      - mongo
  reservations:
    image: CHANGEIT/reservations/production
    env_file:
      - ../apps/reservations/.env
    ports:
      - '3000:3000'
  auth:
    build:
    image: CHANGEIT/auth/production
    env_file:
      - ../apps/auth/.env
    ports:
      - '3001:3001'
  payments:
    image: CHANGEIT/payments/production
    env_file:
      - ../apps/payments/.env
    ports:
      - '3003:3003'
  notifications:
    image: CHANGEIT/notifications/production
    env_file:
      - ../apps/notifications/.env
    ports:
      - '3004:3004'
  mongo:
    image: mongo
